_BASE_: ../default.yaml
exp_name: tci_brats_flair_label=wt_16x_tacklenew-recon_1e-2
callbacks: [TestCallback, PaperFigureCallback]
task: recon
lr: 0.01
model:
  name: TackleNew-Recon
  sampler:
    name: LOUPESampler
    shape: [240, 240]
    subsampling_dim: [-2, -1]
    acceleration: 16
    line_constrained: False
    preselect_num: 0
    preselect_ratio: 128
  reconstructor:
    name: VarNetReconstructor
    num_cascades: 12
    chans: 18
    pools: 4
    acs_ratio: 128
    dc_weight: 1
    adj_dc_weight: True
  predictor:
    name: IdentityPredictor
train_loss:
  name: PSNRLoss
val_test_loss:
  name: PSNR